name: Build APK

on:
  push:
    branches:
      - main  # لو بتستخدم فرع آخر غير main، غيّر الاسم هنا

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build Release APK
      run: |
        cd your-project-directory
        buildozer android release  # بناء نسخة Release
