name: Build APK

on:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    # تثبيت Java JDK 17
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'

    # تثبيت Buildozer باستخدام pip
    - name: Install Buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install Cython
        pip install buildozer

    - name: Check Flutter Doctor
      run: |
        flutter doctor

    - name: Flutter Build APK
      run: |
        flutter config --no-analytics
        flutter build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: warn
        overwrite: false
