name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git zip unzip openjdk-11-jdk python3-pip python3-setuptools libncurses5 libstdc++6 android-sdk android-ndk
          pip install --upgrade pip
          pip install buildozer

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Check APK file existence
        run: |
          ls -lh bin/   # نتحقق إذا كان الـ APK موجود في مجلد bin

      - name: Prepare APK for upload
        run: |
          mkdir -p artifact
          cp bin/*.apk artifact/    # نقوم بنقل الـ APK إلى مجلد artifact
          ls -lh artifact/          # تحقق من محتويات المجلد artifact

      - name: Create archive
        run: |
          tar -czf artifact.tar.gz -C artifact .
          ls -lh artifact.tar.gz  # تحقق من وجود الأرشيف artifact.tar.gz

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: guess-the-flag-apk
          path: artifact.tar.gz
