name: Build Kivy APK (with Buildozer)

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y buildozer git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install Cython
        pip install buildozer

    - name: Initialize Buildozer (if needed)
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
